### ISSUE TITLE
Zips missing?

### ISSUE THREAD

**Issue by yanismydj** [bgruber/zip2fips#3] opened 2014-10-25 00:43 UTC
Love this project, thanks for heading it up.

I'm having trouble with some of the zips missing their corresponding Fips codes(especially ones from San Francisco, ie 94101, 94102-94109, etc).  Do you have any idea why they might be missing?  I'll see if I can find the missing data and submit a PR, but was wondering if you had any more ideas about this.

Thanks!

**Comment by willwest** [comment] 2015-12-11 20:39
See #4 for explanation about why this is happening

**Comment by bgruber** [comment] 2015-12-12 00:45
duplicate of #1

**Closed by bgruber** 2015-12-12 00:45 UTC
